export const data = [
    {
        id: 1,
        img: '../src/assets/img/air.png',
        title: 'Nike Air feminino',
        type: 'Nike',
        categoria: 'Esporte e lazer',
        genero: 'Masculino',
        estado: 'Novo',
        price: 200.00,
        priceDiscount:170.00,
    },
    {
        id: 2,
        img: '../src/assets/img/air.png',
        title: 'Nike Air masculino',
        type: 'Nike',
        categoria: 'Esporte e lazer',
        genero: 'Masculino',
        estado: 'Novo',
        price: 200.00,
        priceDiscount:120.00,
    },
    {
        id: 3,
        img: '../src/assets/img/air.png',
        title: 'Nike Air',
        type: 'Nike',
        categoria: 'Esporte e lazer',
        genero: 'Masculino',
        estado: 'Usado',
        price: 235.00,
    },
    {
        id: 4,
        img: '../src/assets/img/air.png',
        title: 'Nike Air',
        type: 'Nike',
        categoria: 'Esporte e lazer',
        genero: 'Masculino',
        estado: 'Usado',
        price: 200.00,
    },
    {
        id: 5,
        img: '../src/assets/img/k-swiss.png',
        title: 'K-Swiss V8',
        categoria: 'Casual',
        genero: 'Feminino',
        estado: 'Novo',
        type: 'K-Swiss',
        price: 230.00,
        priceDiscount:200.00,
    },
    {
        id: 6,
        img: '../src/assets/img/k-swiss.png',
        title: 'K-Swiss V8',
        categoria: 'Casual',
        genero: 'Feminino',
        estado: 'Novo',
        type: 'K-Swiss',
        price: 230.00,
    },
    {
        id: 7,
        img: '../src/assets/img/k-swiss.png',
        title: 'K-Swiss V8',
        categoria: 'Casual',
        genero: 'Feminino',
        estado: 'Usado',
        type: 'K-Swiss',
        price: 230.00,
    },
    {
        id: 8,
        img: '../src/assets/img/k-swiss.png',
        title: 'K-Swiss V8',
        categoria: 'Casual',
        genero: 'Feminino',
        estado: 'Usado',
        type: 'K-Swiss',
        price: 230.00,
    },
    {
        id: 9,
        img: '../src/assets/img/Adidas.png',
        title: 'Adidas',
        type: 'Adidas',
        categoria: 'Utilitário',
        genero: 'Unisex',
        estado: 'novo',
        price: 250.00,
    },
    {
        id: 10,
        img: '../src/assets/img/Adidas.png',
        title: 'Adidas',
        type: 'Adidas',
        categoria: 'Utilitário',
        genero: 'Unisex',
        estado: 'novo',
        price: 250.00,
    },
    {
        id: 11,
        img: '../src/assets/img/Adidas.png',
        title: 'Adidas',
        type: 'Adidas',
        categoria: 'Utilitário',
        genero: 'Unisex',
        estado: 'Usado',
        price: 250.00,
        priceDiscount:200.00,

    },
    {
        id: 12,
        img: '../src/assets/img/Adidas.png',
        title: 'Adidas',
        type: 'Adidas',
        categoria: 'Utilitário',
        genero: 'Unisex',
        estado: 'Usado',
        price: 250.00,
        priceDiscount:200.00,

    },
    {
        id: 13,
        img: '../src/assets/img/Puma.png',
        title: 'Puma Puma',
        type: 'Puma',
        categoria: 'Corrida',
        genero:'Feminino',
        estad: 'Novo',  
        price: 180.00,
    },
    {
        id: 14,
        img: '../src/assets/img/Puma.png',
        title: 'Puma Puma',
        type: 'Puma',
        categoria: 'Corrida',
        genero:'Feminino',
        estad: 'Novo',  
        price: 180.00,
    },
    {
        id: 15,
        img: '../src/assets/img/Puma.png',
        title: 'Puma Puma',
        type: 'Puma',
        categoria: 'Corrida',
        genero:'Feminino',
        estad: 'Usado',  
        price: 180.00,
    },
    {
        id: 16,
        img: '../src/assets/img/Puma.png',
        title: 'Puma Puma',
        type: 'Puma',
        categoria: 'Corrida',
        genero:'Feminino',
        estad: 'Usado',  
        price: 180.00,
    }
];
